trigger:
- main
- release/*
pr:
- none

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
      macOS:
        imageName: 'macOS-latest'
      Windows:
        imageName: 'windows-latest'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '-o $(Build.ArtifactStagingDirectory)'

    displayName: Build solution

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(imageName)'
      publishLocation: 'Container'
    displayName: Publish build artifacts