trigger:
- none
pr:
- main

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
      macOS:
        imageName: 'macOS-latest'
      Windows:
        imageName: 'windows-latest'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/SerialLoops.sln
    displayName: Build solution

  - task: DotNetCoreCLI@2
    inputs:
      comand: 'test'
      projects: $(Build.SourcesDirectory)/test/SerialLoops.Tests/SerialLoops.Tests.csproj
      publishTestResults: true

